modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/refinedmods/refinedstorage-rei-integration"
license = "MIT"
[[mods]]
modId = "refinedstorage_rei_integration"
version = "${version}"
displayName = "Refined Storage - REI Integration"
displayURL = "https://github.com/refinedmods/refinedstorage-rei-integration"
authors = "Refined Mods"
description = '''
REI integration for Refined Storage.
'''
[[dependencies.refinedstorage_rei_integration]]
modId = "refinedstorage2"
type = "required"
versionRange = "2.0.0-milestone.3.6"
side = "BOTH"
[[dependencies.refinedstorage_rei_integration]]
modId = "roughlyenoughitems"
type = "required"
versionRange = "[14,)"
side = "BOTH"
